# Generated by Django 5.2 on 2025-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('category', models.CharField(default='General', max_length=100)),
                ('temp_field', models.BooleanField(default=False)),
            ],
        ),
    ]
